name: ann-notebook-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - tensorflow
  - keras
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib